# Generated by Django 5.0.6 on 2024-06-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='edad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
