# Generated by Django 5.0.6 on 2024-06-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_flan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='customer_email',
            field=models.EmailField(max_length=40),
        ),
    ]
